version: "3.3"

networks:
  database_kiosk-network:
    external: true

services:
  frontend-dev:
    container_name: ordering-kiosk
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/ordering-kiosk:/app
    ports:
      - "8026:8026"
    restart: unless-stopped
    networks:
      database_kiosk-network:
        ipv4_address: 172.30.0.14


  web-server:
    container_name: webserver-ordering-kiosk
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8003:80"
    volumes:
      - ./app/ordering-kiosk:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-dev
    networks:
      database_kiosk-network:
            ipv4_address: 172.30.0.15