version: "3.8"

networks:
  database_kiosk-network:
    external: true

services:
  backend-dev:
    container_name: kiosk-api
    build:
      context: ./
      dockerfile: ./app/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./app/api:/var/www/html:delegated
    restart: unless-stopped
    networks:
      database_kiosk-network:
        ipv4_address: 172.30.0.5
        
  web-server:
    container_name: kiosk-nginx-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8084:80"
    volumes:
      - ./app/api:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-dev

    restart: unless-stopped
    networks:
      database_kiosk-network:
        ipv4_address: 172.30.0.6 